### ISSUE TITLE
[Bug] [Regression] Cannot get size from a render object that has not been through layout.

### ISSUE THREAD

**Issue by BaranMichal25** [diegoveloper/flutter_percent_indicator#89]
<details>
  <summary>Exception</summary>

```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Cannot get size from a render object that has not been through layout.


The size of this render object has not yet been determined because this render object has not yet been through layout, which typically means that the size getter was called too early in the pipeline (e.g., during the build phase) before the framework has determined the size and position of the render objects during layout.

The size getter was called for the following element: CustomPaint-[GlobalKey#e3044]
  renderObject: RenderCustomPaint#3698b NEEDS-LAYOUT NEEDS-PAINT
The render object from which the size was to be obtained was: RenderCustomPaint#3698b NEEDS-LAYOUT NEEDS-PAINT
...  parentData: not positioned; offset=Offset(0.0, 0.0)
...  constraints: MISSING
...  size: MISSING
When the exception was thrown, this was the stack: 
#0      Element.size.<anonymous closure> (package:flutter/src/widgets/framework.dart:3861:9)
#1      Element.size (package:flutter/src/widgets/framework.dart:3893:6)
#2      _LinearPercentIndicatorState.initState.<anonymous closure>.<anonymous closure> (package:percent_indicator/linear_percent_indicator.dart:149:58)
#3      State.setState (package:flutter/src/widgets/framework.dart:1244:30)
#4      _LinearPercentIndicatorState.initState.<anonymous closure> (package:percent_indicator/linear_percent_indicator.dart:148:9)
...
```
</details>

<details>
  <summary>Stacktrace from my real app</summary>

```
I/flutter (31953): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (31953): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (31953): The following assertion was thrown during a scheduler callback:
I/flutter (31953): Cannot get size from a render object that has not been through layout.
I/flutter (31953): The size of this render object has not yet been determined because this render object has not yet
I/flutter (31953): been through layout, which typically means that the size getter was called too early in the pipeline
I/flutter (31953): (e.g., during the build phase) before the framework has determined the size and position of the
I/flutter (31953): render objects during layout.
I/flutter (31953): The size getter was called for the following element:
I/flutter (31953):   CustomPaint-[GlobalKey#ee9a4]
I/flutter (31953): The render object from which the size was to be obtained was: RenderCustomPaint#0356a NEEDS-LAYOUT NEEDS-PAINT:
I/flutter (31953):   creator: CustomPaint-[GlobalKey#ee9a4] ← Stack ← Padding ← ConstrainedBox ← Container ← Expanded ←
I/flutter (31953):     Row ← ColoredBox ← Container ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (31953):     _InkFeatures-[GlobalKey#86c62 ink renderer] ← ⋯
I/flutter (31953):   parentData: not positioned; offset=Offset(0.0, 0.0)
I/flutter (31953):   constraints: MISSING
I/flutter (31953):   size: MISSING
I/flutter (31953): 
I/flutter (31953): When the exception was thrown, this was the stack:
I/flutter (31953): #0      Element.size.<anonymous closure> (package:flutter/src/widgets/framework.dart:3861:9)
I/flutter (31953): #1      Element.size (package:flutter/src/widgets/framework.dart:3893:6)
I/flutter (31953): #2      _LinearPercentIndicatorState.initState.<anonymous closure>.<anonymous closure> (package:percent_indicator/linear_percent_indicator.dart:149:58)
I/flutter (31953): #3      State.setState (package:flutter/src/widgets/framework.dart:1244:30)
I/flutter (31953): #4      _LinearPercentIndicatorState.initState.<anonymous closure> (package:percent_indicator/linear_percent_indicator.dart:148:9)
I/flutter (31953): #5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (31953): #6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1063:9)
I/flutter (31953): #7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (31953): #11     _invoke (dart:ui/hooks.dart:251:10)
I/flutter (31953): #12     _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter (31953): (elided 3 frames from dart:async)
I/flutter (31953): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

**Steps to reproduce:**
1. Open Pixel emulator (I was able to consistently reproduce it on Pixel 1)
2. Run https://github.com/BaranMichal25/percent_indicator_crash
3. Click PercentIndicator (shows a dialog)
4. Rotate device
5. Close the dialog by clicking somewhere around it
6. Exception is thrown

**Is this a regression?**
Yes - doesn't happen on version `2.1.6`

**Does it crash app?**
No, just throwing exception

**Comment:**
Took me a half-day to create this example and I realise code might look a bit weird, but it's a minified version of a real, legitimate app.
I noticed it also happened to other people here: https://github.com/diegoveloper/flutter_percent_indicator/issues/73 so thought I will share this example.

**Comment by diegoveloper** [comment]
Can you reproduce the issue in a simple and small file ?

**Comment by BaranMichal25** [comment]
That's as small as I could get unfortunately. 
But the bug seems to happen every time, so that's at least useful

**Comment by diegoveloper** [comment]
I just need one file , one simple page to run here and reproduce the issue.

**Comment by juandiago** [comment]
I ran into this exact error, not sure if the cause is the same do. For me, the issue was the use of `UniqueKey` on a widget wrapping the `LinearPercentIndicator`, on subsequent rebuilds, the `UniqueKey` gets replaced and the widget rebuilt so the old one it's not on the layout anymore. 

Replaced the `UniqueKey` with a regular `Key` and everything is ok now.

**Comment by hyungtaecf** [comment]
I have the same issue using it within an Expanded widget, so it does not know the size on the first build and throws the error. It does not affect the user experience, but it throws a lot of red longs in the console because I'm using a long list of them.

Does anybody have any idea how could I fix it?

**Comment by BaranMichal25** [comment]
@hyungtaecf does it also happen on version`2.1.6` ?

**Comment by diegoveloper** [comment]
@hyungtaecf if you can reproduce the issue, please add a minimum sample code.

**Comment by hyungtaecf** [comment]
@BaranMichal25 @diegoveloper Sorry guys, I thought it was the last version. I updated and it is not showing any errors. :)

**Comment by archie-sh** [comment]
Hi, I get this error in flutter web web with the latest version 2.1.9+1 It fills my sentry dashboard

**Comment by dodatw** [comment]
> @BaranMichal25 @diegoveloper Sorry guys, I thought it was the last version. I updated and it is not showing any errors. :)

@hyungtaecf Which version do you use to solve this problem?

**Comment by hyungtaecf** [comment]
> > @BaranMichal25 @diegoveloper Sorry guys, I thought it was the last version. I updated and it is not showing any errors. :)
> 
> @hyungtaecf Which version do you use to solve this problem?

Version 2.1.6

**Comment by pratikbaid3** [comment]
I am getting this error in version ```3.0.1```

Snipet:
```dart
Row(
                  children: [
                    LinearPercentIndicator(
                      padding: EdgeInsets.all(0),
                      width: wp * 0.5,
                      lineHeight: 5.0,
                      percent:
                          widget.model.percentComplete.roundToDouble() / 100,
                      backgroundColor: AppColor.blueAccentColor.withAlpha(80),
                      progressColor:
                          (widget.model.percentComplete.toStringAsFixed(1) ==
                                  '100.0')
                              ? AppColor.greenAccentColor
                              : Colors.blue,
                    ),
                    SizedBox(
                      width: 10,
                    ),
                    Text(
                        widget.model.percentComplete.toStringAsFixed(1) + " %"),
                  ],
                ),
```
The row here is wrapped in a column

Log:
```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Cannot get size from a render object that has not been through layout.


The size of this render object has not yet been determined because this render object has not yet been through layout, which typically means that the size getter was called too early in the pipeline (e.g., during the build phase) before the framework has determined the size and position of the render objects during layout.

The size getter was called for the following element: CustomPaint-[GlobalKey#3a9e9]
  renderObject: RenderCustomPaint#83a0d NEEDS-LAYOUT NEEDS-PAINT
The render object from which the size was to be obtained was: RenderCustomPaint#83a0d NEEDS-LAYOUT NEEDS-PAINT
...  parentData: not positioned; offset=Offset(0.0, 0.0)
...  constraints: MISSING
...  size: MISSING
When the exception was thrown, this was the stack: 
#0      Element.size.<anonymous closure> (package:flutter/src/widgets/framework.dart:3819:9)
#1      Element.size (package:flutter/src/widgets/framework.dart:3851:6)
#2      _LinearPercentIndicatorState.initState.<anonymous closure>.<anonymous closure> (package:percent_indicator/linear_percent_indicator.dart:158:59)
#3      State.setState (package:flutter/src/widgets/framework.dart:1267:30)
#4      _LinearPercentIndicatorState.initState.<anonymous closure> (package:percent_indicator/linear_percent_indicator.dart:157:9)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
Cannot get size from a render object that has not been through layout.
====================================================================================================
```

**Comment by ucshadow** [comment]
Can confirm, getting the same error as @pratikbaid3 , build 3.0.1

**Comment by BaranMichal25** [comment]
For anyone interested: I created a fork of this library and removed code related to widgetIndicator: https://github.com/BaranMichal25/flutter_percent_indicator/commit/fcc3d21a510d465f34dc822edbfdf7ab8692eb73 and it fixed the issue. So far I didn't any get exceptions during development nor in production.

**Comment by diegoveloper** [comment]
Fixed on the latest version.

**Comment by hyungtaecf** [comment]
I get the error again when I wrap it in a Tooltip. Any idea why this is happening?

**Comment by vincentkims49** [comment]
i still got the same error

**Comment by phuppert** [comment]
This exact error is still occurring whenever I try to wrap a LinearPercentIndicator in a Column with another Widget. It doesn't seem to be fixed. Using version 4.2.2 with Flutter 3.7.3.

**Comment by Mahm0ud-Ahmed** [comment]
I also get the same errors

**Comment by Manuito83** [comment]
I fixed this by replacing UniqueKey() by ValueKey() in a ListView, in case it helps.
